## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
# 設定 data_path
dir_data = './data/'

In [16]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)
# print(type(app_train) : dataframe

Path of read in data: ./data/application_train.csv

pandas.core.frame.DataFrame

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [15]:
print("len of column : %d" %len(app_train.columns))
print("len of row : %d" %len(app_train.index))

len of column : 122
len of row : 307511

#### 列出所有欄位

In [17]:
app_train

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9,100012,0,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
12,100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
13,100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
14,100018,0,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,100019,0,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
16,100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
17,100021,0,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18,100022,0,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
19,100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
20,100024,0,Revolving loans,M,Y,Y,0,135000.000,427500.0,21375.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,100025,0,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
22,100026,0,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
23,100027,0,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
24,100029,0,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
25,100030,0,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
26,100031,1,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
27,100032,0,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,0,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
29,100034,0,Revolving loans,M,N,Y,0,90000.000,180000.0,9000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307481,456225,1,Cash loans,M,N,Y,0,225000.000,297000.0,19975.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307482,456226,0,Cash loans,F,Y,Y,0,225000.000,500566.5,34969.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307483,456227,0,Cash loans,F,N,Y,0,99000.000,247275.0,16479.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
307484,456228,0,Cash loans,F,Y,N,0,540000.000,545040.0,35617.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307485,456229,0,Revolving loans,F,N,Y,1,270000.000,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307486,456230,0,Cash loans,F,Y,Y,1,292500.000,355536.0,18283.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
307487,456231,0,Cash loans,M,N,Y,0,117000.000,1071909.0,31473.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,8.0
307488,456232,0,Cash loans,F,N,N,0,157500.000,135000.0,13351.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0
307489,456233,1,Cash loans,F,N,Y,0,225000.000,521280.0,23089.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
307490,456234,0,Cash loans,M,N,Y,0,81000.000,135000.0,9148.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307491,456235,0,Cash loans,M,Y,Y,2,90000.000,1078200.0,31522.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307492,456236,0,Cash loans,M,Y,Y,0,585000.000,1575000.0,43443.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307493,456237,0,Cash loans,F,N,Y,0,135000.000,946764.0,37678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307494,456238,0,Cash loans,M,Y,N,1,270000.000,479700.0,46858.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0
307495,456239,0,Cash loans,M,Y,N,0,180000.000,808650.0,23773.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307496,456240,0,Revolving loans,F,N,N,0,360000.000,337500.0,16875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307497,456241,0,Cash loans,F,Y,Y,0,180000.000,270126.0,12028.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
307498,456242,0,Cash loans,M,Y,Y,0,198000.000,1312110.0,52168.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307499,456243,0,Cash loans,F,N,Y,0,81000.000,225000.0,12694.5,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0
307500,456244,0,Cash loans,F,N,Y,0,261000.000,1303812.0,35982.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0
307501,456245,0,Cash loans,F,N,Y,3,81000.000,269550.0,11871.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307502,456246,0,Cash loans,F,N,Y,1,94500.000,225000.0,10620.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307503,456247,0,Cash loans,F,N,Y,0,112500.000,345510.0,17770.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
307504,456248,0,Cash loans,F,N,Y,0,153000.000,331920.0,16096.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307505,456249,0,Cash loans,F,N,Y,0,112500.000,225000.0,22050.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
307506,456251,0,Cash loans,M,N,N,0,157500.000,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.000,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.000,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.000,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.000,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

#### 截取部分資料

In [35]:
#抽出男性資料擁有車且總收入大於50W
df_M = app_train[(app_train.CODE_GENDER == "M") & (app_train.FLAG_OWN_CAR == "Y") & (app_train.AMT_INCOME_TOTAL>500000)]

print("符合人數 ： %d" %len(df_M.index))

df_M

符合人數 ： 1111

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
51,100059,0,Cash loans,M,Y,Y,1,540000.0,675000.0,34596.0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,3.0
59,100070,0,Cash loans,M,Y,Y,0,540000.0,1227901.5,46899.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
319,100366,0,Revolving loans,M,Y,Y,0,765000.0,1350000.0,67500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
391,100454,0,Revolving loans,M,Y,Y,3,607500.0,1350000.0,67500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
632,100722,0,Cash loans,M,Y,Y,0,540000.0,545040.0,26640.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
701,100810,0,Revolving loans,M,Y,Y,2,540000.0,900000.0,45000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1049,101218,0,Cash loans,M,Y,Y,0,522000.0,746280.0,59094.0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,3.0
1238,101461,0,Cash loans,M,Y,Y,0,810000.0,661500.0,37066.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
1316,101545,0,Cash loans,M,Y,Y,1,630000.0,1257255.0,53397.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1504,101769,0,Revolving loans,M,Y,Y,0,1080000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1942,102276,0,Revolving loans,M,Y,Y,0,540000.0,315000.0,15750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
1959,102297,0,Cash loans,M,Y,Y,2,675000.0,848745.0,46174.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2009,102356,0,Cash loans,M,Y,Y,1,765000.0,1350000.0,51552.0,...,0,0,0,0,0.0,0.0,0.0,1.0,2.0,1.0
3287,103838,0,Cash loans,M,Y,Y,0,810000.0,630000.0,59035.5,...,0,0,0,0,0.0,4.0,3.0,0.0,0.0,1.0
3403,103974,0,Cash loans,M,Y,N,2,540000.0,900000.0,43429.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
3478,104061,0,Cash loans,M,Y,Y,0,540000.0,1255680.0,45234.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
3948,104614,0,Cash loans,M,Y,Y,0,540000.0,835380.0,42781.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4468,105221,0,Cash loans,M,Y,Y,1,607500.0,1350639.0,43699.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
4941,105782,0,Cash loans,M,Y,Y,0,675000.0,450000.0,29299.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5599,106554,0,Cash loans,M,Y,Y,0,540000.0,450000.0,43969.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
5673,106637,0,Cash loans,M,Y,Y,3,967500.0,450000.0,30073.5,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0
5676,106640,0,Revolving loans,M,Y,Y,1,675000.0,585000.0,29250.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
5852,106848,0,Cash loans,M,Y,Y,2,540000.0,497520.0,53712.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
6069,107099,0,Cash loans,M,Y,Y,2,540000.0,935640.0,98379.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
6292,107343,0,Revolving loans,M,Y,Y,0,652500.0,1350000.0,67500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
6764,107892,0,Revolving loans,M,Y,Y,0,675000.0,675000.0,33750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
7694,108971,0,Cash loans,M,Y,Y,1,540000.0,497520.0,52920.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
8048,109385,0,Cash loans,M,Y,Y,1,675000.0,521280.0,35392.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
8086,109431,0,Revolving loans,M,Y,Y,0,900000.0,225000.0,11250.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8365,109747,0,Cash loans,M,Y,Y,1,585000.0,1546020.0,42642.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299335,446780,0,Cash loans,M,Y,Y,0,540000.0,983160.0,62964.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
299646,447139,0,Revolving loans,M,Y,Y,0,673380.0,202500.0,10125.0,...,1,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
299756,447269,0,Cash loans,M,Y,N,0,675000.0,1762110.0,48586.5,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,1.0
300586,448235,0,Cash loans,M,Y,Y,0,585000.0,450000.0,29299.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
301058,448783,0,Cash loans,M,Y,Y,0,900000.0,1786500.0,98028.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
301608,449414,0,Cash loans,M,Y,Y,0,540000.0,1379376.0,40329.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,4.0
301622,449430,0,Cash loans,M,Y,N,0,540000.0,1125000.0,109728.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
301728,449559,0,Revolving loans,M,Y,Y,0,900000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
301947,449814,0,Revolving loans,M,Y,Y,0,675000.0,900000.0,45000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
302323,450259,0,Cash loans,M,Y,Y,0,540000.0,1227901.5,46899.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
302798,450814,0,Cash loans,M,Y,Y,0,675000.0,1223010.0,48501.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
302848,450870,0,Cash loans,M,Y,Y,0,571500.0,808650.0,22234.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
303364,451479,0,Revolving loans,M,Y,Y,0,675000.0,225000.0,11250.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
303519,451658,0,Cash loans,M,Y,Y,3,675000.0,720000.0,75735.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
303520,451659,0,Cash loans,M,Y,N,1,540000.0,755190.0,34992.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
303550,451695,0,Cash loans,M,Y,Y,3,585000.0,900000.0,26316.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
303825,452013,0,Cash loans,M,Y,N,0,540000.0,1206000.0,111730.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
304075,452302,0,Cash loans,M,Y,N,1,900000.0,1347466.5,71923.5,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,3.0
304302,452563,0,Cash loans,M,Y,N,0,630000.0,1288350.0,41692.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
304378,452646,0,Cash loans,M,Y,N,0,675000.0,1412095.5,96984.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
304671,452985,0,Revolving loans,M,Y,N,0,675000.0,1350000.0,67500.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
305068,453446,0,Cash loans,M,Y,N,0,540000.0,1327855.5,56389.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
305369,453799,0,Cash loans,M,Y,N,0,675000.0,341280.0,27094.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
305577,454039,0,Cash loans,M,Y,Y,0,1215000.0,1264738.5,67513.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,3.0
306005,454539,0,Cash loans,M,Y,N,0,675000.0,1078200.0,31522.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
306028,454569,0,Revolving loans,M,Y,Y,0,1350000.0,1575000.0,78750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
306179,454746,0,Cash loans,M,Y,Y,1,949500.0,735579.0,35518.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
306882,455551,0,Cash loans,M,Y,Y,0,517500.0,2250000.0,59485.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307002,455682,0,Cash loans,M,Y,N,0,546250.5,1800000.0,166572.0,...,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307492,456236,0,Cash loans,M,Y,Y,0,585000.0,1575000.0,43443.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子